import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, TextInput, View } from "react-native";
import NetInfo from "@react-native-community/netinfo";
import { WebView } from "react-native-webview";
import type { Page, User, Workspace } from "@notionlike/contracts";
import { parseEditorMessage, type NativeToEditorMessage } from "@notionlike/editor/bridge";
import { credentials, cachePages, cachedPages, flushOutbox } from "./src/storage";

type Session = { serverUrl: string; token: string };
const normalizeServer = (value: string) => value.trim().replace(/\/$/, "");

export default function App() {
  const [session, setSession] = useState<Session | null>(); const [online, setOnline] = useState(true);
  useEffect(() => { void credentials.load().then((saved) => setSession(saved.serverUrl && saved.token ? { serverUrl: saved.serverUrl, token: saved.token } : null)); const subscription = NetInfo.addEventListener((state) => setOnline(Boolean(state.isConnected))); return subscription; }, []);
  if (session === undefined) return <Loading />;
  if (!session) return <SignIn onAuthenticated={(next) => { setSession(next); void credentials.save(next.serverUrl, next.token); }} />;
  return <WorkspaceHome session={session} online={online} onLogout={() => { void credentials.clear(); setSession(null); }} />;
}

function Loading() { return <View style={styles.center}><ActivityIndicator color="#2383e2" /></View>; }
function SignIn({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [serverUrl, setServerUrl] = useState("http://10.0.2.2:3000"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const login = async () => { setBusy(true); setError(""); const server = normalizeServer(serverUrl); try { const meta = await fetch(`${server}/api/v1/meta`); if (!meta.ok) throw new Error("This is not a compatible NotionLike server"); const response = await fetch(`${server}/api/v1/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); onAuthenticated({ serverUrl: server, token: body.token }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Connection failed"); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.auth}><StatusBar barStyle="dark-content" /><View style={styles.authCard}><View style={styles.logo}><Text style={styles.logoText}>N</Text></View><Text style={styles.heading}>Connect to your workspace</Text><Text style={styles.muted}>Use the address of your self-hosted NotionLike server.</Text><Text style={styles.label}>Server URL</Text><TextInput style={styles.input} value={serverUrl} autoCapitalize="none" keyboardType="url" onChangeText={setServerUrl} /><Text style={styles.label}>Email</Text><TextInput style={styles.input} value={email} autoCapitalize="none" keyboardType="email-address" onChangeText={setEmail} /><Text style={styles.label}>Password</Text><TextInput style={styles.input} value={password} secureTextEntry onChangeText={setPassword} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={styles.primary} disabled={busy} onPress={() => void login()}><Text style={styles.primaryText}>{busy ? "Connecting…" : "Sign in"}</Text></Pressable></View></SafeAreaView>;
}

function WorkspaceHome({ session, online, onLogout }: { session: Session; online: boolean; onLogout: () => void }) {
  const [user, setUser] = useState<User>(); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspace, setWorkspace] = useState<Workspace>(); const [pages, setPages] = useState<Page[]>([]); const [selected, setSelected] = useState<Page>(); const [error, setError] = useState("");
  const api = useMemo(() => async <T,>(path: string, init: RequestInit = {}) => { const response = await fetch(`${session.serverUrl}/api/v1${path}`, { ...init, headers: { "content-type": "application/json", Authorization: `Bearer ${session.token}`, ...init.headers } }); const body = response.status === 204 ? undefined : await response.json(); if (!response.ok) throw new Error(body?.error ?? "Request failed"); return body as T; }, [session]);
  useEffect(() => { if (!online) return; void Promise.all([api<{ user: User }>("/auth/me"), api<{ workspaces: Workspace[] }>("/workspaces")]).then(([me, result]) => { setUser(me.user); setWorkspaces(result.workspaces); setWorkspace(result.workspaces[0]); void flushOutbox(api); }).catch((reason) => setError(String(reason))); }, [api, online]);
  useEffect(() => { if (!workspace) return; const local = cachedPages(workspace.id); if (local.length) setPages(local); if (online) void api<{ pages: Page[] }>(`/workspaces/${workspace.id}/pages`).then((result) => { setPages(result.pages); cachePages(workspace.id, result.pages); }); }, [api, online, workspace]);
  if (selected) return <EditorScreen session={session} page={selected} online={online} onBack={() => setSelected(undefined)} />;
  return <SafeAreaView style={styles.app}><View style={styles.header}><View><Text style={styles.eyebrow}>{online ? "SYNCED" : "OFFLINE CACHE"}</Text><Text style={styles.title}>{workspace?.name ?? "Workspace"}</Text></View><Pressable onPress={onLogout}><Text style={styles.link}>Sign out</Text></Pressable></View>{error ? <Text style={styles.errorBanner}>{error}</Text> : null}<FlatList data={pages.filter((page) => !page.archived)} keyExtractor={(page) => page.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>✦</Text><Text style={styles.heading}>No pages yet</Text><Text style={styles.muted}>Create your first page on the web or when connected.</Text></View>} renderItem={({ item }) => <Pressable style={styles.pageRow} onPress={() => setSelected(item)}><Text style={styles.pageIcon}>{item.icon ?? "📄"}</Text><View style={styles.pageText}><Text style={styles.pageTitle}>{item.title || "Untitled"}</Text><Text style={styles.muted}>{item.parentId ? "Nested page" : "Page"}</Text></View><Text style={styles.chevron}>›</Text></Pressable>} /><Text style={styles.account}>{user?.email}</Text></SafeAreaView>;
}

function EditorScreen({ session, page, online, onBack }: { session: Session; page: Page; online: boolean; onBack: () => void }) {
  const webview = useRef<WebView>(null); const [ready, setReady] = useState(false); const [sync, setSync] = useState("loading");
  const initialize = () => { const message: NativeToEditorMessage = { type: "initialize", apiBaseUrl: `${session.serverUrl}/api/v1`, token: session.token, pageId: page.id }; webview.current?.postMessage(JSON.stringify(message)); };
  return <SafeAreaView style={styles.app}><View style={styles.editorHeader}><Pressable onPress={onBack}><Text style={styles.back}>‹ Pages</Text></Pressable><Text numberOfLines={1} style={styles.editorTitle}>{page.icon ?? "📄"} {page.title}</Text><Text style={styles.sync}>{online ? sync : "offline"}</Text></View><WebView ref={webview} source={{ uri: `${session.serverUrl}/mobile/editor/${page.id}` }} cacheEnabled domStorageEnabled javaScriptEnabled onLoadEnd={() => { setReady(true); initialize(); }} onMessage={(event) => { const message = parseEditorMessage(event.nativeEvent.data); if (message?.type === "ready") initialize(); if (message?.type === "sync") setSync(message.state); }} renderLoading={() => <Loading />} startInLoadingState />{!ready && <Loading />}</SafeAreaView>;
}

const styles = StyleSheet.create({ center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" }, auth: { flex: 1, justifyContent: "center", backgroundColor: "#f7f7f5", padding: 22 }, authCard: { gap: 9, borderRadius: 18, backgroundColor: "#fff", padding: 24 }, logo: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderWidth: 2, borderRadius: 8, marginBottom: 12 }, logoText: { fontSize: 22, fontFamily: "serif", fontWeight: "700" }, heading: { fontSize: 23, fontWeight: "700", color: "#2f2f2f" }, muted: { color: "#787774", fontSize: 13 }, label: { marginTop: 9, color: "#4b4b48", fontSize: 12, fontWeight: "600" }, input: { borderWidth: 1, borderColor: "#deded9", borderRadius: 8, padding: 11, color: "#222" }, error: { color: "#b42318", paddingTop: 5 }, primary: { alignItems: "center", borderRadius: 8, backgroundColor: "#2383e2", padding: 13, marginTop: 13 }, primaryText: { color: "#fff", fontWeight: "700" }, app: { flex: 1, backgroundColor: "#fff" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: "#ddd" }, eyebrow: { color: "#999", fontSize: 10, fontWeight: "700", letterSpacing: 1 }, title: { color: "#222", fontSize: 20, fontWeight: "700" }, link: { color: "#2383e2" }, list: { padding: 12 }, pageRow: { minHeight: 62, flexDirection: "row", alignItems: "center", padding: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: "#e8e8e4" }, pageIcon: { fontSize: 23, marginRight: 12 }, pageText: { flex: 1, gap: 3 }, pageTitle: { color: "#292927", fontSize: 16, fontWeight: "500" }, chevron: { color: "#aaa", fontSize: 28 }, empty: { alignItems: "center", paddingTop: 100, gap: 8 }, emptyIcon: { color: "#2383e2", fontSize: 40 }, account: { color: "#999", fontSize: 11, padding: 12, textAlign: "center" }, errorBanner: { color: "#b42318", backgroundColor: "#fef3f2", padding: 10 }, editorHeader: { height: 52, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: "#ddd" }, back: { color: "#2383e2", fontSize: 16 }, editorTitle: { flex: 1, textAlign: "center", fontWeight: "600" }, sync: { width: 45, color: "#888", fontSize: 10, textAlign: "right" } });
