import { randomUUID } from "node:crypto";
import type { FastifyInstance } from "fastify";
import * as Y from "yjs";
import { authenticate } from "./auth.js";
import { pageAccess, sql, workspaceRole } from "./db.js";

const makeDocument=(text:string)=>{const doc=new Y.Doc();const root=doc.getXmlFragment("default");for(const line of text.split(/\r?\n/)){const node=new Y.XmlElement(/^#{1,3} /.test(line)?"heading":"paragraph");if(node.nodeName==="heading")node.setAttribute("level",String(Math.min(3,line.match(/^#+/)?.[0].length??1)));node.insert(0,[new Y.XmlText(line.replace(/^#{1,3} /,""))]);root.insert(root.length,[node]);}return Y.encodeStateAsUpdate(doc)};
const plainText=(doc:Y.Doc)=>doc.getXmlFragment("default").toString().replace(/<[^>]+>/g,"\n").replace(/\n+/g,"\n").trim();
export async function registerContentRoutes(app:FastifyInstance){
 app.post("/api/v1/workspaces/:workspaceId/import",{preHandler:authenticate},async(request,reply)=>{const{workspaceId}=request.params as any;const role=await workspaceRole(request.user.id,workspaceId);if(!role||role==="guest")return reply.code(403).send({error:"Forbidden"});const body=request.body as {format?:string;name?:string;content?:string};if(!body.content||!["markdown","html","text"].includes(body.format??""))return reply.code(400).send({error:"Supported formats: markdown, html, text"});const text=body.format==="html"?body.content.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g,""):body.content;const id=randomUUID();await sql.begin(async tx=>{await tx`INSERT INTO pages(id,workspace_id,title,position,created_by) VALUES(${id},${workspaceId},${body.name??"Imported note"},COALESCE((SELECT max(position)+1 FROM pages WHERE workspace_id=${workspaceId}),0),${request.user.id})`;await tx`INSERT INTO page_updates(page_id,client_id,sequence,update_data) VALUES(${id},'import',0,${Buffer.from(makeDocument(text))})`});return reply.code(201).send({pageId:id});});
 app.get("/api/v1/pages/:pageId/export",{preHandler:authenticate},async(request,reply)=>{const{pageId}=request.params as any;if(!await pageAccess(request.user.id,pageId))return reply.code(403).send({error:"Forbidden"});const{format="markdown"}=request.query as any;const updates=await sql<{updateData:Buffer}[]>`SELECT update_data FROM page_updates WHERE page_id=${pageId} ORDER BY id`;const doc=new Y.Doc();for(const row of updates)Y.applyUpdate(doc,new Uint8Array(row.updateData));const text=plainText(doc);if(format==="json")return {document:doc.getXmlFragment("default").toJSON()};if(format==="html"){reply.type("text/html");return `<article>${text.split("\n").map(x=>`<p>${x.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!))}</p>`).join("")}</article>`;}reply.type("text/markdown");return text;});
 app.get("/api/v1/workspaces/:workspaceId/plugins",{preHandler:authenticate},async(request,reply)=>{const{workspaceId}=request.params as any;if(!await workspaceRole(request.user.id,workspaceId))return reply.code(403).send({error:"Forbidden"});return{plugins:await sql`SELECT * FROM workspace_plugins WHERE workspace_id=${workspaceId} ORDER BY installed_at`}});
 app.post("/api/v1/workspaces/:workspaceId/plugins",{preHandler:authenticate},async(request,reply)=>{const{workspaceId}=request.params as any;const role=await workspaceRole(request.user.id,workspaceId);if(!["owner","admin"].includes(role??""))return reply.code(403).send({error:"Forbidden"});const manifest=request.body as any;if(!manifest?.key||!manifest?.name||!manifest?.version||!Array.isArray(manifest.capabilities))return reply.code(400).send({error:"Invalid plugin manifest"});const allowed=["editor.toolbar","page.action","database.property","theme.css"];if(manifest.capabilities.some((x:string)=>!allowed.includes(x)))return reply.code(400).send({error:"Unsupported capability"});const rows=await sql`INSERT INTO workspace_plugins(workspace_id,plugin_key,name,version,manifest,installed_by) VALUES(${workspaceId},${manifest.key},${manifest.name},${manifest.version},${sql.json(manifest)},${request.user.id}) ON CONFLICT(workspace_id,plugin_key) DO UPDATE SET name=excluded.name,version=excluded.version,manifest=excluded.manifest RETURNING *`;return reply.code(201).send({plugin:rows[0]});});
 app.patch("/api/v1/workspace-plugins/:id",{preHandler:authenticate},async(request,reply)=>{const{id}=request.params as any;const[plugin]=await sql<{workspaceId:string}[]>`SELECT workspace_id FROM workspace_plugins WHERE id=${id}`;if(!plugin||!["owner","admin"].includes(await workspaceRole(request.user.id,plugin.workspaceId)??""))return reply.code(403).send({error:"Forbidden"});const rows=await sql`UPDATE workspace_plugins SET enabled=${Boolean((request.body as any)?.enabled)} WHERE id=${id} RETURNING *`;return{plugin:rows[0]};});
}
